name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # - windows-latest
          # The Dune Developer Preview does not currently support MINGW64_NT-10.0-26100 x86_64.
        ocaml-compiler:
          - 5.4.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use dune
        uses: ocaml-dune/setup-dune@v1

      - name: Lock dependencies
        run: dune pkg lock

      - name: Build
        run: dune build

      - name: Run tests
        run: dune runtest

      - name: Check code formatting
        run: dune build @fmt
